# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 17:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of news', max_length=100)),
                ('category', models.CharField(blank=True, help_text='Category of the news', max_length=100)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2017, 10, 29, 20, 46, 42, 765763), help_text='Publication date of the news')),
                ('announce', models.TextField(help_text='Announce of the news')),
                ('text', models.TextField(help_text='Text of the news')),
                ('image', models.ImageField(blank=True, help_text='Image of the news', upload_to='')),
            ],
        ),
    ]
